# Importamos librerías para manejar variables de entorno y FastAPI
from dotenv import load_dotenv
from fastapi import FastAPI

# Importamos el router de retos (modulo de python)
from app.const import CONN_STRING
from app.routers import challenge
from app.routers import view

load_dotenv()  # Carga las variables de entorno desde el archivo .env


# Librerias para inicializar la db
async def create_tables(conn_string):
  # manejo de Errores de la db
  try:
    # abre una extension de conexión a la db
    with conn_string as conn:
      # crea un cursor para ejecutar comandos SQL
      with conn.cursor() as cur:
        # ejecuta el comando SQL para crear la tabla de retos
        cur.execute(
          """
          CREATE TABLE IF NOT EXISTS challenges (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(100),
            description TEXT
          );
          """
        )
  # manejo de errores
  except Exception as err:
    print(f"Error al crear las tablas: {err}")


# Ejecutamos la creación de tablas
create_tables(CONN_STRING)

# Inicializamos la aplicación FastAPI
app = FastAPI()
# Incluimos el router de retos en la aplicación principal
app.include_router(challenge.router)
app.include_router(view.router)
