# Importamos las librerías necesarias para nuestra practica
import os

from dotenv import load_dotenv
from fastapi import FastAPI

from app.routers import challenge

load_dotenv()  # Carga las variables de entorno desde el archivo .env

conn_string = os.getenv("DATABASE_URL")


async def create_tables(conn_string):
  try:
    with conn_string as conn:
      print("Conexión exitosa a la base de datos.")
      with conn.cursor() as cur:
        cur.execute(
          """
          CREATE TABLE IF NOT EXISTS challenges (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(100),
            description TEXT
          );
          """
        )
  except Exception as err:
    print(f"Error al crear las tablas: {err}")


create_tables(conn_string)

# Inicializamos la aplicación FastAPI
app = FastAPI()
app.include_router(challenge.router)
